### ISSUE TITLE
https://www.ietf.org/id/draft-ietf-cellar-ffv1-v4-07.html

### ISSUE THREAD

**Issue by digitensions** [digitensions/AVstandards#1]
FFV1 standard missing, look for alternative or let Dave know! :)

**Comment by ablwr** [comment]
https://datatracker.ietf.org/doc/draft-ietf-cellar-ffv1-v4/

**Comment by ablwr** [comment]
All the related specs can be found on the IETF CELLAR's Documents page https://datatracker.ietf.org/wg/cellar/documents/

**Comment by digitensions** [comment]
Thank you Ashley! I'll update it :)
